### ISSUE TITLE
Suggestion: For Fixed Amount Payments

### ISSUE THREAD

**Issue by oladipo** [PaystackHQ/plugin-payment-forms-for-wordpress#24]
It will be good to display the amount a customer pays as a label i.e <div>[Amount</div> as against <input type=text value=[Amount]> for fixed payments.

I get the feeling that a more advanced user could maybe edit this value by enabling the disabled amount field in their browser.

Just saying.

**Comment by steveamaza** [comment]
Fixed in previous releases
